# Generated by Django 4.1.3 on 2022-11-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0003_rename_usuario_publicacoes_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacoes',
            name='criado_em',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='publicacoes',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
    ]
