# Generated by Django 4.1.3 on 2022-11-10 23:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BLOG', '0004_alter_publicacoes_criado_em_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publicacoes',
            new_name='Publicacoe',
        ),
    ]
