# Generated by Django 4.1.2 on 2022-11-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0006_rename_publicacoe_publicacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacoes',
            name='imagem',
            field=models.ImageField(upload_to='pub_img'),
        ),
    ]
